### ISSUE TITLE
Intermittent issue - Status attribute is not always updated when secret is created.

### ISSUE THREAD

**Issue by ldimaggi** [baijum/postgresql-operator#8]
Seeing an intermittent issue where the credential attribute is not populated when a secret is created:

```
spec:
  dbName: postgres
  image: docker.io/postgres
  imageName: postgres
status:
  dbConnectionIP: 172.30.105.222
  dbConnectionPort: 5432
  dbCredentials: ""
  dbName: postgres
```
The dbCredentials points to a secret that the db operator creates, so the reason why it is empty is probably the failed update of the status field after the secret was created. (Tt happens sometimes and most of the time deletion and re-creation of the DB CR helps).
