### ISSUE TITLE
Replaces meta data for operator in CSV throws fatal error when no previous version of operator is found

### ISSUE THREAD

**Issue by ldimaggi** [baijum/postgresql-operator#9]
Started seeing this issue (https://github.com/operator-framework/operator-registry/issues/47) since the postgresql-operator was updated. 

The updated (v0.0.4) operator's manifest explicitly replaces the previous version of the operator:

```
  version: REPLACE_VERSION
  replaces: postgresql-operator.v0.0.3
```
However, this causes the installation of the operator to fail unless the quay repo contains a v0.0.3 instance of the operator:

``` yaml:
  containerStatuses:
    - name: db-operators
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            Back-off 5m0s restarting failed container=db-operators
            pod=db-operators-54bc68548b-ngp9c_openshift-marketplace(83c21748-a1af-11e9-a9c5-02519ac499b2)
      lastState:
        terminated:
          exitCode: 1
          reason: Error
          message: >
            time="2019-07-08T19:04:48Z" level=fatal msg="error loading manifest
            from remote registry - postgresql-operator.v0.0.4 specifies
            replacement that couldn't be found" port=50051 type=appregistry
          startedAt: '2019-07-08T19:04:47Z'
          finishedAt: '2019-07-08T19:04:48Z'
```
